name: Deploy to Staging

on:
  push:
    branches: [develop, staging]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://staging.derail.me

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to Railway (Staging)
        run: |
          # Install Railway CLI
          npm install -g @railway/cli

          # Deploy to staging
          echo "🚂 Deploying to Railway staging..."
          railway login --boarding-token ${{ secrets.RAILWAY_TOKEN }}
          railway up --service staging-chittypro

        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Render (Alternative Staging)
        if: failure()
        run: |
          echo "🔄 Railway failed, trying Render..."
          # Alternative deployment to Render
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      - name: Run staging tests
        run: |
          echo "🧪 Running staging environment tests..."
          # Wait for deployment
          sleep 30

          # Health check
          for i in {1..10}; do
            if curl -f https://staging.derail.me/api/health; then
              echo "✅ Staging environment is healthy"
              break
            else
              echo "⏳ Waiting for staging environment... ($i/10)"
              sleep 10
            fi
          done

      - name: Notify staging deployment
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Staging deployment successful: https://staging.derail.me"
          else
            echo "❌ Staging deployment failed"
          fi